# Generated by Django 5.0 on 2026-06-17 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_profile_contract_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='weekly_hours',
            field=models.DecimalField(decimal_places=4, max_digits=6),
        ),
        migrations.AlterField(
            model_name='profile',
            name='weekly_target_hours',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Override target hours per week. If empty, uses weekly hours.', max_digits=6, null=True, verbose_name='Weekly target hours'),
        ),
    ]
