# Generated by OpenCode

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0005_alter_profile_weekly_hours_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="target_hours_period",
            field=models.CharField(
                choices=[("weekly", "Weekly"), ("monthly", "Monthly")],
                default="weekly",
                max_length=10,
                verbose_name="Target hours period",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="monthly_target_hours",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="Target hours per month. Used when target hours period is monthly.",
                max_digits=7,
                null=True,
                verbose_name="Monthly target hours",
            ),
        ),
    ]
