# Generated by Django 5.0 on 2026-08-26 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_profile_monthly_target_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='archived_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
