# Generated by Django 5.0 on 2026-09-01 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_profile_archived_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='TargetHoursChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_from', models.DateField(blank=True, help_text='First day of the month this change is effective from. Empty means baseline, valid since the beginning.', null=True)),
                ('target_hours_period', models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly')], default='weekly', max_length=10)),
                ('weekly_hours', models.DecimalField(decimal_places=4, max_digits=6)),
                ('weekly_target_hours', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('monthly_target_hours', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_hours_changes', to='profiles.profile')),
            ],
        ),
        migrations.AddConstraint(
            model_name='targethourschange',
            constraint=models.UniqueConstraint(condition=models.Q(('valid_from__isnull', False)), fields=('profile', 'valid_from'), name='uniq_target_hours_change_per_month'),
        ),
        migrations.AddConstraint(
            model_name='targethourschange',
            constraint=models.UniqueConstraint(condition=models.Q(('valid_from__isnull', True)), fields=('profile',), name='uniq_target_hours_baseline'),
        ),
    ]
